analytics: {}
color:
  brandColors:
    - '#C0C0B8'
    - '#000000'
    - '#889090'
    - '#000000'
    - '#000000'
  brandStrength: 0.6875
  lightness: 0.375
  rhythmicContrast: 0.5
  saturation: 0.5
cta: {}
layout_spectrum: 0.64903
name: Kenneth Power MD
opengraph: {}
purpose: []
typography_spectrum: 0.41356
