name: Kenneth Power MD
favicon: null
layout_spectrum: 0.64903
typography_spectrum: 0.1083360358607024
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fafaf8'
    - '#292d30'
    - '#8f95a1'
    - '#986e55'
    - '#7d1d31'
  brandStrength: 0.6875
  lightness: 0.375
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
