name: Kenneth Power MD
favicon: null
layout_spectrum: 0
typography_spectrum: 0.823198
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#C8D0B8'
    - '#000000'
    - '#B0A878'
    - '#000000'
    - '#000000'
  brandStrength: 0.25
  lightness: 0.875
  saturation: 0.6875
  rhythmicContrast: 0.761261
purpose: []
