analytics: {}
color:
  brandColors:
    - '#B08098'
    - '#780010'
    - '#905870'
    - '#F02850'
    - '#D8A0B8'
  brandStrength: 0.233108
  lightness: 0.806306
  rhythmicContrast: 0.838964
  saturation: 0.739864
cta: {}
layout_spectrum: 0.944819
name: Kenneth Power MD
opengraph: {}
purpose: []
typography_spectrum: 1
