analytics: {}
color:
  brandColors:
    - '#C8D0B8'
    - '#000000'
    - '#B0A878'
    - '#000000'
    - '#000000'
  brandStrength: 0.686936
  lightness: 0.764639
  rhythmicContrast: 0.628378
  saturation: 0.68018
cta: {}
layout_spectrum: 0.322072
name: Kenneth Power MD
opengraph: {}
purpose: []
typography_spectrum: 0.739864
