analytics: {}
color:
  brandColors:
    - '#C8D0B8'
    - '#000000'
    - '#B0A878'
    - '#000000'
    - '#000000'
  brandStrength: 0.361486
  lightness: 1
  rhythmicContrast: 0.766891
  saturation: 0.835585
cta: {}
layout_spectrum: 0.850225
name: Kenneth Power MD
opengraph: {}
purpose: []
typography_spectrum: 0.643018
