analytics: {}
color:
  brandColors:
    - '#A8A0B8'
    - '#20B090'
    - '#906068'
    - '#18C0C0'
    - '#000000'
  brandStrength: 0.578828
  lightness: 0.726351
  rhythmicContrast: 0.787162
  saturation: 0.657657
cta: {}
layout_spectrum: 0.693693
name: Kenneth Power MD
opengraph: {}
purpose: []
typography_spectrum: 0.926801
