analytics: {}
color:
  brandColors:
    - '#C8D0B8'
    - '#000000'
    - '#B0A878'
    - '#000000'
    - '#000000'
  brandStrength: 0.334459
  lightness: 0.947072
  rhythmicContrast: 0.648648
  saturation: 0.792792
cta: {}
layout_spectrum: 0.850225
name: Kenneth Power MD
opengraph: {}
purpose: []
typography_spectrum: 0.691441
